name: CI

on:
  push:
  pull_request:

env:
  COVERAGE_PHP_VERSION: "8.4"

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        deps:
          - "highest"
        include:
          - php-version: "8.2"
            deps: "lowest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.deps }}

      - name: Run PHPUnit
        run: vendor/bin/phpunit
        if: ${{ matrix.php-version != env.COVERAGE_PHP_VERSION }}

      - name: Run PHPUnit with coverage
        run: vendor/bin/phpunit --coverage-clover clover.xml
        if: ${{ matrix.php-version == env.COVERAGE_PHP_VERSION }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ matrix.php-version == env.COVERAGE_PHP_VERSION }}

  psalm:
    name: Psalm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install composer dependencies (date-time)
        uses: ramsey/composer-install@v3

      - name: Install composer dependencies (psalm)
        uses: ramsey/composer-install@v3
        with:
          working-directory: "tools/psalm"

      - name: Run Psalm
        run: tools/psalm/vendor/bin/psalm --show-info=false --no-progress --config=tools/psalm/psalm.xml

  coding-standard:
    name: Coding Standard
    uses: brick/coding-standard/.github/workflows/coding-standard.yml@v4
    with:
      working-directory: "tools/ecs"
